// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3DWTLj5bmxTQObyiwu0oCB_wsDZQp0s',
    appId: '1:699796051937:web:4437aa0b1e267e186464a0',
    messagingSenderId: '699796051937',
    projectId: 'chat-5c360',
    authDomain: 'chat-5c360.firebaseapp.com',
    storageBucket: 'chat-5c360.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5Yfww2_F2ENb17qR7LXmJAnKzE5olm4',
    appId: '1:699796051937:android:56af4531abf8d3386464a0',
    messagingSenderId: '699796051937',
    projectId: 'chat-5c360',
    storageBucket: 'chat-5c360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcsi0g9qGWS22DS8BTuquzIigUJFlyc8',
    appId: '1:699796051937:ios:20a14b7cbbd639ef6464a0',
    messagingSenderId: '699796051937',
    projectId: 'chat-5c360',
    storageBucket: 'chat-5c360.appspot.com',
    iosBundleId: 'com.example.testAssignmentChat',
  );
}
